# Generated by Django 4.1.1 on 2022-10-16 20:55

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_commentpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentpost",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
    ]
